# Generated by Django 3.2.2 on 2021-05-09 13:50

import audio_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.CharField(max_length=1000, validators=[audio_files.models.participant_validation]),
        ),
    ]
