# Generated by Django 3.2.2 on 2021-05-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
