# Generated by Django 3.2.2 on 2021-05-09 05:19

import audio_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0002_auto_20210509_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='duration',
            field=models.DurationField(validators=[audio_files.models.duration_validation]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.DurationField(validators=[audio_files.models.duration_validation]),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(validators=[audio_files.models.duration_validation]),
        ),
    ]
