# Generated by Django 3.2.2 on 2021-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0004_auto_20210509_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.CharField(max_length=1000),
        ),
    ]
