# Generated by Django 3.2.2 on 2021-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0005_alter_podcast_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
